accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path("logout/", auth_views.logout_then_login, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path

from todolist import views

app_name = 'todolist'

urlpatterns = [
    path('create/', views.ToDoItemCreateView.as_view(), name='create'),
    path('update/<pk>/', views.ToDoItemUpdateView.as_view(), name='update'),
    path('delete/<pk>/', views.ToDoItemDeleteView.as_view(), name='delete'),
    path('', views.ToDoItemListView.as_view(), name='home'),
    path('detail/<pk>/', views.ToDoItemDetailView.as_view(), name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.contrib.auth.models import User
from django.db import models


class ToDoItem(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=255)
    text = models.TextField(blank=True)

accounts/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView


class IsNotAuthenticatedUser:
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('todolist:home')

        return super().dispatch(request, *args, **kwargs)


class LoginView(IsNotAuthenticatedUser, auth_views.LoginView):
    next_page = 'todolist:home'


class RegisterView(IsNotAuthenticatedUser, CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'registration/register.html'

todolist/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.urls import reverse_lazy
from django.views import generic

from todolist.models import ToDoItem


class ToDoItemMixin(LoginRequiredMixin):
    model = ToDoItem
    fields = ['title', 'text']
    success_url = reverse_lazy('todolist:home')

    def get_queryset(self):
        qs: QuerySet = super().get_queryset()

        qs = self.__filter_user_items(qs)

        return qs

    def __filter_user_items(self, qs: QuerySet):
        return qs.filter(user=self.request.user)

    def get_success_url(self):
        next = self.request.GET.get('next')

        if next:
            return next

        return super().get_success_url()


class ToDoItemCreateView(ToDoItemMixin, generic.CreateView):
    def form_valid(self, form):
        response = super().form_valid(form)

        self.object.user_id = self.request.user.pk
        self.object.save()

        return response


class ToDoItemUpdateView(ToDoItemMixin, generic.UpdateView):
    pass


class ToDoItemDeleteView(ToDoItemMixin, generic.DeleteView):
    pass


class ToDoItemListView(ToDoItemMixin, generic.ListView):
    template_name = 'todolist/home.html'


class ToDoItemDetailView(ToDoItemMixin, generic.DetailView):
    pass

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'assets/css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
  {% block css %}{% endblock css %}
  <title>TODO
    {% block title %}{% endblock title %}
  </title>
</head>

<body>
  <div class="fundo-escuro">
    <header class="layout cabecalho">
      <h1>
        <a href="{% url 'todolist:home' %}">TODO</a>
      </h1>
      <div>
        {% if request.user.is_authenticated %}
          <p>{{ request.user.username }} | <a href="{% url 'accounts:logout' %}">Deslogar</a></p>
          <a href="{% url 'todolist:create' %}">Criar TODO</a>
        {% endif %}
      </div>
    </header>
  </div>

  <div class="fundo-claro">
    <main class="layout conteudo">
      {% block content %}{% endblock content %}
    </main>
  </div>

  <div class="fundo-escuro">
    <footer class="layout rodape">
      <p>
        TODO List feita por
        <a href="https://github.com/vitormcferreira" target="_blank">@Vitor Ferreira</a>
        usando Django
      </p>
    </footer>
  </div>
</body>

</html>

templates/base_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
  <h2 class="titulo">{% block content_title %}{% endblock content_title %}</h2>

  <form method="POST" class="form">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% with WIDGET_ERROR_CLASS='form-field-error' %}
      {% block fields %}{% endblock fields %}
    {% endwith %}

    <button type="submit" class="button form-button">{% block button_text %}{% endblock button_text %}</button>
    <p>{% block text_after_button %}{% endblock text_after_button %}</p>
  </form>
{% endblock content %}

todolist/templates/todolist/home.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'todolist/assets/css/home.css' %}">
{% endblock css %}

{% block content %}
  {% for todoitem in object_list %}
    <article class="todoitem">
      <h2>
        <a href="{% url 'todolist:detail' pk=todoitem.pk %}">{{ todoitem.title }}</a>
      </h2>
      <div>
        <a href="{% url 'todolist:update' pk=todoitem.pk %}" class="button">Editar</a>
        <a href="{% url 'todolist:delete' pk=todoitem.pk %}" class="button">Apagar</a>
      </div>
    </article>
  {% endfor %}
{% endblock content %}

todolist/templates/todolist/todoitem_confirm_delete.html
{% extends 'base_form.html' %}

{% load widget_tweaks %}

{% block title %}
 - Apagar TODO
{% endblock title %}

{% block content_title %}Apagar TODO{% endblock content_title %}

{% block fields %}
  <p>Deseja realmente apagar "{{ object.title }}"?</p>
{% endblock fields %}

{% block button_text %}Sim{% endblock button_text %}

todolist/templates/todolist/todoitem_detail.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'todolist/assets/css/todoitem_detail.css' %}">
{% endblock css %}

{% block title %} - Detalhes{% endblock title %}

{% block content %}
  <article class="todoitem-detail">
    <section>
      <a href="{% url 'todolist:update' pk=todoitem.pk %}?next={% url 'todolist:detail' pk=todoitem.pk %}" class="button">Editar</a>
      <a href="{% url 'todolist:delete' pk=todoitem.pk %}" class="button">Apagar</a>
    </section>
    
    <header>
      <h2 class="titulo">
        {{ object.title }}
      </h2>
    </header>
    <main>
      
      <p>{{ object.text }}</p>
    </main>
  </article>
{% endblock content %}

todolist/templates/todolist/todoitem_form.html
{% extends 'base_form.html' %}

{% load widget_tweaks %}

{% block title %}
 - {% if request.resolver_match.url_name == 'create' %}Criar{% else %}Atualizar{% endif %}
{% endblock title %}

{% block content_title %}
  {% if request.resolver_match.url_name == 'create' %}Criar{% else %}Atualizar{% endif %} TODO
{% endblock content_title %}

{% block fields %}
  {% render_field form.title class='form-input' placeholder='*Título' %}
  {{ form.title.errors }}
  {% render_field form.text class='form-input' placeholder='Texto' %}
  {{ form.text.errors }}
{% endblock fields %}

{% block button_text %}Salvar{% endblock button_text %}